---
kind: pipeline
type: docker
name: build

steps:
  - name: docker
    image: docker:dind
    privileged: true
    detach: true
    command: [ "dockerd", "--host=tcp://0.0.0.0:2375" ]

  - name: version
    image: alpine:3.13
    commands:
    - apk add --update --no-cache curl git jq
    - LATEST=$(curl -s https://api.github.com/repos/kiwiirc/webircgateway/commits | jq -r '.[0].sha' | cut -c1-7)
    - if curl -sfL https://hub.docker.com/v2/repositories/ezkrg/webircgateway/tags/$LATEST > /dev/null; then echo "tag $LATEST already exist"; exit 78; fi
    - echo -n "$LATEST" > .tag

  - name: build
    image: ezkrg/buildx:latest
    environment:
      USER:
        from_secret: DHU
      PASSWORD:
        from_secret: DHP
      DOCKER_HOST: tcp://docker:2375
    commands:
    - while ! docker info; do sleep 1; done
    - TAG=$(cat .tag)
    - docker buildx create --use --name docker --node docker --platform linux/amd64 --driver docker-container $DOCKER_HOST
    - echo $PASSWORD | docker login --username $USER --password-stdin
    - docker buildx build --load --cache-from ezkrg/cache:webircgateway --cache-to ezkrg/cache:webircgateway -t ezkrg/webircgateway:$TAG --build-arg VERSION=$TAG .
    - docker push ezkrg/webircgateway:$TAG
    - docker tag ezkrg/webircgateway:$TAG ezkrg/webircgateway:latest
    - docker push ezkrg/webircgateway:latest
---
kind: signature
hmac: ca6b291f88a85c5083047b86e479a3179d92cd07d9787ae0bddda06c80e07870

...
